{% set name = "argparse-manpage-birdtools" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 20eae3079a4a2dbe1a7557ef7276a4d8e5a44c7c4223afb50f4f1d0ae0e7d103

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - build_manpages

about:
  home: https://github.com/wwood/argparse-manpage-birdtools
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Format ROFF documents (manual page format) from python ArgumentParser objects. Maintained specifically for the bird tools bioinformatics suite.

extra:
  recipe-maintainers:
    - wwood
    - rhysnewell
